theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
encoding: utf-8

### minimal mistakes
# logo: "/assets/img/face.jpg"
#minimal_mistakes_skin: "air"
title: "Tatu Lahtelas blog"
name: "Tatu Lahtela"
description: "Tatu Lahtelas personal blog"
include:
  - _pages
twitter:
  username: "ttration"
defaults:
   - scope:
       path: ""
       type: posts
     values:
      read_time: true
      comments: true
      share: true
      classes: wide
paginate: 5 # amount of posts to show
paginate_path: /page:num/
author:
  name             : "Tatu Lahtela"
  avatar           : "/assets/img/face.jpg"
  bio              : "Programmer"
  github           : "ration"
  twitter          : "ttration"
  linkedin         : "tatu-lahtela-38868a26?trk=nav_responsive_tab_profile_pic"

highlighter: rouge
exclude: ["deploy.sh"]
